image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and push Image '
          services:
            - docker
          caches:
            - docker
          script:
            - export IMAGE_NAME=registry.noseryoung.ch/noseryoung/restdb:latest
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME